"""
UR3e agent definition for ManiSkill3.

Robot: UR3e arm (6 DOF) + simple parallel gripper (2 prismatic fingers)
Controller: PDEEPoseController (EEF delta 6DOF) + PDJointPosMimicController (gripper)
Action dim: 7  [dx, dy, dz, droll, dpitch, dyaw, gripper]  ← matches pi0 output

URDF: /opt/ur3e/ur3e_with_gripper.urdf  (generated by scripts/generate_ur3e_urdf.py)
      Override via env var UR3E_URDF.
"""

from __future__ import annotations

import os
from copy import deepcopy
from typing import Union

import numpy as np
import sapien
import torch

from mani_skill.agents.base_agent import BaseAgent, Keyframe
from mani_skill.agents.controllers.pd_ee_pose import (
    PDEEPoseControllerConfig,
    PDEEPosControllerConfig,
)
from mani_skill.agents.controllers.pd_joint_pos import (
    PDJointPosControllerConfig,
    PDJointPosMimicControllerConfig,
)
from mani_skill.agents.registration import register_agent
from mani_skill.utils import common
from mani_skill.utils.structs.actor import Actor

# ── URDF path ─────────────────────────────────────────────────────────────────
_DEFAULT_URDF = "/opt/ur3e/ur3e_with_gripper.urdf"
UR3E_URDF = os.environ.get("UR3E_URDF", _DEFAULT_URDF)

# ── Joint names (must match the URDF generated by generate_ur3e_urdf.py) ─────
ARM_JOINTS = [
    "shoulder_pan_joint",
    "shoulder_lift_joint",
    "elbow_joint",
    "wrist_1_joint",
    "wrist_2_joint",
    "wrist_3_joint",
]
GRIPPER_JOINTS = ["left_finger_joint", "right_finger_joint"]  # right_finger mimics left
TCP_LINK = "gripper_tcp_link"           # frame between fingertips


@register_agent()
class UR3e(BaseAgent):
    """UR3e with simple parallel gripper for ManiSkill3."""

    uid: str = "ur3e"
    urdf_path: str = UR3E_URDF

    # Home position: arm upright, gripper open
    # qpos: [6 arm joints, left_finger, right_finger]
    keyframes = dict(
        rest=Keyframe(
            pose=sapien.Pose(p=[0, 0, 0]),
            qpos=np.array(
                [0.0, -1.5708, 1.5708, -1.5708, -1.5708, 0.0, 0.04, 0.04],
                dtype=np.float32,
            ),
        )
    )

    # PD gains
    arm_stiffness: float = 1e3
    arm_damping: float = 1e2
    arm_force_limit: float = 100.0

    gripper_stiffness: float = 1e3
    gripper_damping: float = 1e2
    gripper_force_limit: float = 20.0

    ee_link_name: str = TCP_LINK

    @property
    def finger1_link(self):
        return self.robot.links_map["left_finger_link"]

    @property
    def finger2_link(self):
        return self.robot.links_map["right_finger_link"]

    def is_static(self, threshold: float = 0.2):
        qvel = self.robot.get_qvel()[..., :-2]  # exclude finger joints
        return torch.max(torch.abs(qvel), 1)[0] <= threshold

    def is_grasping(self, object: Union[Actor, None] = None, min_force: float = 0.5, max_angle: float = 85):
        l_contact_forces = self.scene.get_pairwise_contact_forces(self.finger1_link, object)
        r_contact_forces = self.scene.get_pairwise_contact_forces(self.finger2_link, object)
        lforce = torch.linalg.norm(l_contact_forces, axis=1)
        rforce = torch.linalg.norm(r_contact_forces, axis=1)
        # fingers open along X axis in local frame
        ldirection = self.finger1_link.pose.to_transformation_matrix()[..., :3, 0]
        rdirection = -self.finger2_link.pose.to_transformation_matrix()[..., :3, 0]
        langle = common.compute_angle_between(ldirection, l_contact_forces)
        rangle = common.compute_angle_between(rdirection, r_contact_forces)
        lflag = torch.logical_and(lforce >= min_force, torch.rad2deg(langle) <= max_angle)
        rflag = torch.logical_and(rforce >= min_force, torch.rad2deg(rangle) <= max_angle)
        return torch.logical_and(lflag, rflag)

    @property
    def _controller_configs(self) -> dict:
        # ── Arm: joint position (non-delta) ───────────────────────────────────
        arm_pd_joint_pos = PDJointPosControllerConfig(
            ARM_JOINTS,
            lower=None,
            upper=None,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            normalize_action=False,
        )

        # ── Arm: joint delta position ─────────────────────────────────────────
        arm_pd_joint_delta_pos = PDJointPosControllerConfig(
            ARM_JOINTS,
            lower=-0.1,
            upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            use_delta=True,
            normalize_action=True,
        )

        # ── Arm: EEF delta pose (6DOF) — used by pi0 ─────────────────────────
        arm_pd_ee_delta_pose = PDEEPoseControllerConfig(
            joint_names=ARM_JOINTS,
            pos_lower=-0.1,
            pos_upper=0.1,
            rot_lower=-0.1,
            rot_upper=0.1,
            stiffness=self.arm_stiffness,
            damping=self.arm_damping,
            force_limit=self.arm_force_limit,
            ee_link=self.ee_link_name,
            urdf_path=self.urdf_path,  # pinocchio IK に使用
        )

        # ── Gripper: joint position (mimic) ───────────────────────────────────
        # mimic dict: right_finger follows left_finger (multiplier=1.0)
        gripper_pd_joint_pos = PDJointPosMimicControllerConfig(
            joint_names=GRIPPER_JOINTS,
            lower=0.0,   # fully closed
            upper=0.04,  # fully open
            stiffness=self.gripper_stiffness,
            damping=self.gripper_damping,
            force_limit=self.gripper_force_limit,
            normalize_action=True,
            mimic={"right_finger_joint": {"joint": "left_finger_joint", "multiplier": 1.0, "offset": 0.0}},
        )

        return dict(
            # pi0 向け: EEF delta pose + gripper
            pd_ee_delta_pose=dict(
                arm=arm_pd_ee_delta_pose,
                gripper=gripper_pd_joint_pos,
            ),
            # デバッグ向け: joint delta pos
            pd_joint_delta_pos=dict(
                arm=arm_pd_joint_delta_pos,
                gripper=deepcopy(gripper_pd_joint_pos),
            ),
            # 軌道制御向け: joint pos
            pd_joint_pos=dict(
                arm=arm_pd_joint_pos,
                gripper=deepcopy(gripper_pd_joint_pos),
            ),
        )
